### ISSUE TITLE
Beta Roadmap

### ISSUE THREAD

**Issue by Kuret** [Kuret/just_in_tappd#2]
- [x] Adding products with basic info
- [x] Filling info from Untappd's API
- [ ] Scanning barcodes to fill info
- [ ] Manage stock through 'Sales' and 'Purchase Orders'
- [ ] Adding suppliers and breweries
- [ ] Adding beer styles
- [ ] Predefined percentages for margins and discounts (+BTW?)

**Comment by RonaldDijkstra** [comment]
- [ ] Basic styling

**Comment by RonaldDijkstra** [comment]
Adding styles > Can be the list of Untappd.
